name: release

on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:

permissions:
    contents: write

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                go-version-file: go.mod
            - name: Create App Token
              uses: actions/create-github-app-token@v1
              id: create-token
              with:
                app_id: ${{ secrets.APP_ID }}
                private_key: ${{ secrets.PRIVATE_KEY }}
            - name: Run GoReleaser
              uses: goreleaser/goreleaser-action@v4
              with:
                distribution: goreleaser
                version: latest
                args: release --clean
              env:
                GITHUB_TOKEN: ${{ secrets.create-token.outputs.token }}